spring:
  application:
    name: sangdari
  datasource:
    url: ${SPRING_DB_URL}
    username: ${SPRING_DB_USERNAME}
    password: ${SPRING_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.sangdari
  configuration:
    map-underscore-to-camel-case: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  max-age: ${CORS_MAX_AGE}

storage:
  files:
    # 마지막 '/'가 빠지면 파일접근 안정
    location: storage/files/

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_SECRET_KEY}

security:
  jwt:
    secure: false
    issuer: ${SECURITY_JWT_ISSUER}
    type: ${SECURITY_JWT_TYPE}
    access-token-expiry: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRY}
    refresh-token-expiry: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRY}
    refresh-token-cookie-name: ${SECURITY_JWT_REFRESH_TOKEN_COOKIE_NAME}
    refresh-token-cookie-expiry: ${SECURITY_JWT_REFRESH_TOKEN_COOKIE_EXPIRY}
    secret: ${SECURITY_JWT_SECRET_KEY}
    header-key: ${SECURITY_JWT_HEADER_KEY}
    scheme: ${SECURITY_JWT_SCHEME}
    reissue-uri: ${SECURITY_JWT_REISSUE_URI}

logging:
  file:
    name: logs/error.log
  level:
    com.example.project.mapper: debug